#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

ROS_DISTRO="${ROS_DISTRO:-humble}"
SEEDS="${SEEDS:-0 1 2}"
SCENARIOS="${SCENARIOS:-static_clutter pedestrian_dynamic mixed_complex}"
ALGORITHMS="${ALGORITHMS:-ippo mappo maddpg mo_gat_mappo}"
EVAL_BASE="${EVAL_BASE:-results/eval}"
OUTPUT_ROOT="${OUTPUT_ROOT:-results/eval/formal_stage1_comparison}"
GENERATE_TRAJECTORY_FIGURES="${GENERATE_TRAJECTORY_FIGURES:-1}"

source scripts/source_setup_file.sh "/opt/ros/${ROS_DISTRO}/setup.bash"
source scripts/source_setup_file.sh install/setup.bash

mkdir -p "${OUTPUT_ROOT}"

merge_args=()
input_count=0
for algorithm in ${ALGORITHMS}; do
  for seed in ${SEEDS}; do
    metrics="${EVAL_BASE}/formal_stage1_${algorithm}_seed${seed}/all_metrics.csv"
    if [[ -f "${metrics}" ]]; then
      merge_args+=(--input "${metrics}")
      input_count=$((input_count + 1))
    else
      echo "Skipping missing metrics: ${metrics}"
    fi
  done
done

if [[ "${input_count}" -eq 0 ]]; then
  echo "No formal metrics found to merge." >&2
  exit 1
fi

ros2 run mrpp_experiments merge_mrpp_results \
  "${merge_args[@]}" \
  --output "${OUTPUT_ROOT}/all_metrics.csv"

python3 scripts/normalize_result_config_columns.py "${OUTPUT_ROOT}/all_metrics.csv"

ros2 run mrpp_paper plot_mrpp_metrics \
  --input "${OUTPUT_ROOT}/all_metrics.csv" \
  --output "${OUTPUT_ROOT}/metric_summary.csv"

if [[ "${GENERATE_TRAJECTORY_FIGURES}" == "1" ]]; then
  mkdir -p "${OUTPUT_ROOT}/figures"
  for algorithm in ${ALGORITHMS}; do
    for seed in ${SEEDS}; do
      root="${EVAL_BASE}/formal_stage1_${algorithm}_seed${seed}"
      for scenario_name in ${SCENARIOS}; do
        trajectory="${root}/${scenario_name}/eval_seed${seed}_trajectories.csv"
        if [[ ! -f "${trajectory}" ]]; then
          continue
        fi
        scenario="src/mrpp_experiments/config/scenarios/${scenario_name}.yaml"
        figure="${OUTPUT_ROOT}/figures/${algorithm}_seed${seed}_${scenario_name}.png"
        ros2 run mrpp_paper plot_mrpp_trajectories \
          --trajectory "${trajectory}" \
          --scenario "${scenario}" \
          --output "${figure}" \
          --title "${algorithm} ${scenario_name} seed${seed}"
      done
    done
  done
fi

cat > "${OUTPUT_ROOT}/README.md" <<EOF
# Formal Stage 1 Comparison

Generated by \`scripts/make_formal_tables.sh\`.

- Combined metrics: \`${OUTPUT_ROOT}/all_metrics.csv\`
- Mean/std summary: \`${OUTPUT_ROOT}/metric_summary.csv\`
- Trajectory figures: \`${OUTPUT_ROOT}/figures/\`

Only rows with existing per-seed evaluation outputs are included. Final paper
tables should use the mean/std summary after all planned seeds have completed.
EOF

echo "Formal tables and figures written to ${OUTPUT_ROOT}."
