<?xml version="1.0"?>
<package format="3">
  <name>mrpp_rl</name>
  <version>0.0.0</version>
  <description>Reinforcement learning algorithms for cooperative multi-robot path planning.</description>
  <maintainer email="884237172@qq.com">lixiang-886</maintainer>
  <license>Apache-2.0</license>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_msgs</depend>
  <depend>mrpp_gazebo</depend>
  <depend>mrpp_navigation</depend>
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
