name: unseen_dense_crossing_n6
world: unseen_dense_crossing
max_steps: 2400
dt: 0.1
robots:
  - name: robot_1
    start: {x: 7.0, y: 0.0, yaw: 3.1416}
    goal: {x: -7.0, y: 0.0, yaw: 3.1416}
  - name: robot_2
    start: {x: 3.5, y: 6.062, yaw: -2.0944}
    goal: {x: -3.5, y: -6.062, yaw: -2.0944}
  - name: robot_3
    start: {x: -3.5, y: 6.062, yaw: -1.0472}
    goal: {x: 3.5, y: -6.062, yaw: -1.0472}
  - name: robot_4
    start: {x: -7.0, y: 0.0, yaw: 0.0}
    goal: {x: 7.0, y: 0.0, yaw: 0.0}
  - name: robot_5
    start: {x: -3.5, y: -6.062, yaw: 1.0472}
    goal: {x: 3.5, y: 6.062, yaw: 1.0472}
  - name: robot_6
    start: {x: 3.5, y: -6.062, yaw: 2.0944}
    goal: {x: -3.5, y: 6.062, yaw: 2.0944}
